name: cd

on:
  push:
    branches: [main]

jobs: 
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
          
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
      
      - name: Build binary
        run: scripts/buildprod.sh

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: notely-467607

      - name: Push image to Artifact Registry
        run: |
          gcloud auth configure-docker europe-north2-docker.pkg.dev
          gcloud builds submit \
            --tag europe-north2-docker.pkg.dev/notely-467607/notely-ar-repo/notely:latest \
            .

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest
      
      - name: Run database migrations
        run: goose -dir db/migrations postgres "$DATABASE_URL" up

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image europe-north2-docker.pkg.dev/notely-467607/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-467607 --max-instances=4