name: cd

on:
  push:
    branches: [main]

jobs: 
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
          
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
      
      - name: Build binary
        run: scripts/buildprod.sh

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: true-episode-467607-t2
          install_components: docker

      - name: Push image to Artifact Registry
        run: |
          gcloud auth configure-docker europe-north2-docker.pkg.dev
          gcloud builds submit \
            --tag europe-north2-docker.pkg.dev/notely-467607/notely-ar-repo/notely:latest \
            .